#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo sed -i '/errorfile 504/a listen webdtb' /etc/haproxy/haproxy.cfg
sudo sed -i '/listen webdtb/a         bind :80' /etc/haproxy/haproxy.cfg
sudo sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sudo sed -i '/mode http/a       balance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '/balance roundrobin/a         server 514569-web-01 100.26.18.107:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/server 514569-web-01 100.26.18.107:80 check/a         server 514569-web-02 18.210.33.88:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo service haproxy start
~                                     
